import { App } from 'vue';
import DwWechatLogin from './dwWechatLogin/src/DwWechatLogin.vue';
import DwDragVerify from './dwDragVerify/src/DwDragVerify.vue';
import DwPortfolioBg from './dwPortfolioBg/src/DwPortfolioBg.vue';
import DwPortfolioIcon from './dwPortfolioIcon/src/DwPortfolioIcon.vue';
import DwPortfolioLine from './dwPortfolioLine/src/DwPortfolioLine.vue';
import DwPortfolioPie from './dwPortfolioPie/src/DwPortfolioPie.vue';
import DwPortfolioIndustry from './dwPortfolioIndustry/src/DwPortfolioIndustry.vue';
import DwStocksAnalysisLine, { AnalyzeType, ReportType } from './dwStocksAnalysisLine/src/DwStocksAnalysisLine.vue';
import DwFilterSlider from './dwFilterSlider/src/DwFilterSlider.vue';
import DwFilterArea from './dwFilterArea/src/DwFilterArea.vue';
import DwFilterRuler from './dwFilterRuler/src/DwFilterRuler.vue';
import DwFilterAreaSlider from './dwFilterAreaSlider/src/DwFilterAreaSlider.vue';
import DwFilterRulerSlider from './dwFilterRulerSlider/src/DwFilterRulerSlider.vue';
export { DwFilterSlider, DwFilterArea, DwFilterRuler, DwFilterAreaSlider, DwFilterRulerSlider, DwStocksAnalysisLine, AnalyzeType, ReportType, DwPortfolioBg, DwPortfolioIcon, DwPortfolioLine, DwPortfolioPie, DwPortfolioIndustry, DwWechatLogin, DwDragVerify, };
declare const _default: {
    version: string;
    install: (app: App<any>) => void;
};
export default _default;
